spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skill-race
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
server:
  port: 8080
